baseURL = 'https://ananthvyas.me/'
locale = 'en-us'
title = "Ananth Vyas"
theme = 'PaperMod'

[params]
  defaultTheme = 'auto'
  showReadingTime = true
  showShareButtons = false
  showPostNavLinks = true

[params.homeInfoParams]
  Title = "Hi, I'm Ananth 👋"
  Content = "I'm a hobby woodworker and a wannabe storyteller."

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/posts/"
  weight = 10

[[menu.main]]
  identifier = "woodworking"
  name = "Woodworking"
  url = "/woodworking/"
  weight = 20

[[menu.main]]
  identifier = "stories"
  name = "Storytelling"
  url = "/stories/"
  weight = 30
